services:
  nestjs-app:
    container_name: techknowledge-api-nest-container
    image: techknowledge-api-nest
    restart: always
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./nestjs-app:/usr/src/app
    tty: true
    networks:
      - techknowledge-network
    # depends_on:
    #   - db

  # db:
  #   image: postgres
  #   container_name: technowledge_db
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   tty: true
  #   volumes:
  #     - ./postgres:/var/lib/postgres
  #   environment:
  #     POSTGRES_DB: db_tech
  #     POSTGRES_PASSWORD: postgres


networks:
  techknowledge-network:
    driver: bridge