services:
  nestjs-app:
    container_name: techknowledge-api-nest-container
    image: mikkaiserdev/techknowledge-api-nest-container:${IMAGE_TAG}
    restart: always
    ports:
      - "3000:3000"
    environment:
      - URL_DATABASE=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - .:/usr/src/app
    tty: true
    networks:
      - techknowledge-network
    depends_on:
      - postgres

  postgres:
    image: postgres:17.4
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - techknowledge-network

networks:
  techknowledge-network:
    external: true
    name: techknowledge-network

volumes:
  postgres_data: