version: '3.8'

services:
  app:
    build: .
    container_name: technowledge_api
    entrypoint: dockerize -wait tcp://db:5432 -timeout 11s docker-entrypoint.sh
    ports:
      - 3000:3000
    # networks:
    #   - tech-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  db:
    image: postgres
    container_name: technowledge_db
    restart: always
    ports:
      - 5432:5432
    tty: true
    volumes:
      - ./postgres:/var/lib/postgres
    environment:
      POSTGRES_DB: db_tech
      POSTGRES_PASSWORD: postgres
    # networks:
    #   - tech-network
# networks:
#   tech-network:
#     driver: bridge
